#version 450

layout(
  local_size_x = 4,
  local_size_y = 4,
  local_size_z = 4) in;

layout(binding = 0)
writeonly uniform image3D dst;

layout(push_constant)
uniform u_info_t {
  vec4 clear_value;
  ivec4 dst_offset;
  ivec4 dst_extent;
} u_info;

void main() {
  ivec3 thread_id = ivec3(gl_GlobalInvocationID);
  
  if (all(lessThan(thread_id.xyz, u_info.dst_extent.xyz))) {
    imageStore(dst,
      u_info.dst_offset.xyz + thread_id.xyz,
      u_info.clear_value);
  }
}