name: Artifacts (Linux Native)

on: [push, pull_request, workflow_dispatch]

jobs:
  artifacts-linux-native:
    runs-on: ubuntu-latest
    container: 
      image: registry.gitlab.steamos.cloud/steamrt/sniper/sdk:beta
      options: --user 1001

    steps:
    - name: Checkout code
      id: checkout-code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Setup problem matcher
      uses: Joshua-Ashton/gcc-problem-matcher@v3

    - name: Build release
      id: build-release
      shell: bash
      run: |
        export VERSION_NAME="${GITHUB_REF##*/}-${GITHUB_SHA##*/}"
        ./package-native.sh ${VERSION_NAME} build --clang-btver2
        echo "VERSION_NAME=${VERSION_NAME}" >> $GITHUB_ENV

    - name: Upload artifacts
      id: upload-artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dxvk-native-${{ env.VERSION_NAME }}
        path: build/dxvk-native-${{ env.VERSION_NAME }}.tar.gz
        if-no-files-found: error
